title: My Github homepage
description: It's a good idea to give a description
theme: jekyll-theme-cayman
lsi: false
safe: true
incremental: false
markdown: Pandoc
highlighter: rouge
gems:
  - jekyll-pandoc
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

pandoc:
  extensions:
    - normalize
    - smart
    - mathjax
    - csl: _styles/apa.csl
    - bibliography: bibliography/references.bib