title: My Github homepage
description: It's a good idea to give a description
theme: jekyll-theme-cayman
lsi: false
safe: true
incremental: false
markdown: kramdown
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter", "math"]